In [46]:
print("jason") #printing name

jason


#Import Laibary

In [47]:
import numpy as np

In [48]:
print(np.__version__) #Check the version of numpy

2.1.3


In [49]:
arr =np.array([1,2,3,4]) #create a Numpy array
arr

array([1, 2, 3, 4])

In [50]:
print(type(arr)) #check the class

<class 'numpy.ndarray'>


0-D Array

In [51]:
arr = np.array(100)
arr

array(100)

In [52]:
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
100


1-D Array

In [53]:
arr1 = np.array([1,2,3])
print(arr1)
print(type(arr1))

[1 2 3]
<class 'numpy.ndarray'>


2-D Array

In [54]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(type(arr2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


3-D Array

In [55]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)
print(type(arr3))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>


check the dimentions

In [56]:
print("0-D",arr.ndim)
print("1-D",arr1.ndim)
print("2-D",arr2.ndim)
print("3-D",arr3.ndim)

0-D 0
1-D 1
2-D 2
3-D 3


other way to create dimention like

In [63]:
a = np.array(0)
b = np.array([1])
c = np.array([[2]])
d = np.array([[[3]]])
print(a,b,c,d)
print("0-D",a.ndim)
print("1-D",b.ndim)
print("2-D",c.ndim)
print("3-D",d.ndim)

0 [1] [[2]] [[[3]]]
0-D 0
1-D 1
2-D 2
3-D 3


higher dimantion array

In [64]:
jh = np.array([1,2,3,4,5])

In [66]:
print(jh)
print(type(jh))
print(jh.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [69]:
jh = np.array([1,2,3,4,5], ndmin=10) # ndimn(number of dimantion) = 10 means 10-D array
print(jh)
print(type(jh))
print(jh.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
<class 'numpy.ndarray'>
10


assess array elements

In [ ]:
jh1 = np.array([1,2,3,4])
print(jh1)
print(type(jh1))
print(jh1.ndim)
print(jh1[0]) #find position of 1 

[1 2 3 4]
<class 'numpy.ndarray'>
1
1


In [74]:
#like(0=1,1=2,2=3,3=4) 
print(jh1[3]) #find position of 4 

4


In [77]:
#ADD array
jh1 = np.array([1,2,3,4])
print(jh1[0] + jh1[3]) #0=1 & 3=4 result will be 1+4=5

5


access 2, 3 Dimantion array elements

In [107]:
arr2 = np.array([[1,2,3],[4,5,6]]) #2-D
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #3-D
print(arr2)
print(arr3)

[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#find 1, 3, 5 from arr2(2-D)
print(arr2 [0,0]) 
print(arr2 [0,2])
print(arr2 [1,1]) 

1
3
5


In [109]:
#find 1, 3, 5, 9, 11 from arr3(3-D)
print(arr3 [0,0,0]) 
print(arr3 [0,0,2])
print(arr3 [0,1,1]) 
print(arr3 [1,0,2])
print(arr3 [1,1,1])

1
3
5
9
11


negative indexing

In [116]:
#find 5, 3, 1 from arr2(2-D)
print(arr2 [-1,-2]) 
print(arr2 [0,-1])
print(arr2 [0,-3]) 

5
3
1


slicing arrays

In [1]:
#[start:end]
#[start:end:step]