In [1]:
import numpy as np

In [2]:
np.__version__

'2.0.2'

In [3]:
a = np.array(0)
a

array(0)

In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print("The dimention is",a.ndim)

The dimention is 0


In [9]:
a = np.array([[[0,1,5]]])
print(type(a))
print("The dimention is",a.ndim)

<class 'numpy.ndarray'>
The dimention is 3


In [11]:
#2d array
b = np.array([[1,2,3],[4,5,6]])
print(b)
print("The dimention is",b.ndim)

[[1 2 3]
 [4 5 6]]
The dimention is 2


In [14]:
#3d array
b = np.array([[[1,2,3],[4,5,6]],[[2,3,5],[6,5,2]]])
print(b)
print("The dimention is",b.ndim)

[[[1 2 3]
  [4 5 6]]

 [[2 3 5]
  [6 5 2]]]
The dimention is 3


In [21]:
a = (1,2,3,4,5,6,74,56)
b = np.array(a, ndmin=10)
print(b)
print("The dimention is",b.ndim)

[[[[[[[[[[ 1  2  3  4  5  6 74 56]]]]]]]]]]
The dimention is 10


In [24]:
a = (1,2,3,4,5,6)
c = (12,13,15,16,18,19)
b = np.array([a,c], ndmin=2)
print(b)
print("The dimention is",b.ndim)

[[ 1  2  3  4  5  6]
 [12 13 15 16 18 19]]
The dimention is 2


In [26]:
a = (1,2,3,4,5,6)
c = (12,13,15,16,18,19)
d = (19,16,15,18,1,3)
b = np.array([a,c,d], ndmin=3)
print(b)
print("The dimention is",b.ndim)

[[[ 1  2  3  4  5  6]
  [12 13 15 16 18 19]
  [19 16 15 18  1  3]]]
The dimention is 3


In [30]:
#access array
b = np.array([1,2,3,4,5,6,7,10]) #.astype("int32")
b[1]

np.int64(2)

In [31]:
#access array
b = np.array([1,2,3,4,5,6,7,10]) #.astype("int32")
b

array([ 1,  2,  3,  4,  5,  6,  7, 10])

In [33]:
b = np.array(["jason","halder"])
b

array(['jason', 'halder'], dtype='<U6')

In [35]:
b[1]

np.str_('halder')

In [36]:
b[0]

np.str_('jason')

In [40]:
#2d array
b = np.array([[1,2,3],[4,5,6]])
print(b)
b[1][-1]

[[1 2 3]
 [4 5 6]]


np.int64(6)

In [43]:
#3d array
b = np.array([[[1,2,3],[4,5,6]],[[2,3,5],[6,5,2]]])
print(b)
b[0][0][0]

[[[1 2 3]
  [4 5 6]]

 [[2 3 5]
  [6 5 2]]]


np.int64(1)

In [44]:
b[0][1][0]

np.int64(4)

In [49]:
b[1,0,0:3]

array([2, 3, 5])

In [52]:
arr = np.array([1,2,3,4,"True"])
print(arr.dtype)

<U21


In [53]:
arr

array(['1', '2', '3', '4', 'True'], dtype='<U21')

In [58]:
arr = np.array([1,2,3,4])
print(arr)
arr.shape

[1 2 3 4]


(4,)

In [59]:
b = np.array([[[1,2,3],[4,5,6]],[[2,3,5],[6,5,2]]])
print(b.shape)
print(b)

(2, 2, 3)
[[[1 2 3]
  [4 5 6]]

 [[2 3 5]
  [6 5 2]]]


In [60]:
arr = np.array([1,2,3,4])
print(arr)
b=arr.reshape(2,2)
print(b)

[1 2 3 4]
[[1 2]
 [3 4]]


In [61]:
for i in b:
  for j in i:
    print(j)

1
2
3
4


In [66]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([4, 5, 6, 7])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 4 5 6 7]


In [67]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[4, 5], [6, 7]])
arr = np.concatenate((arr1, arr2))
print(arr)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [68]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[4, 5], [6, 7]])
arr = np.concatenate(((arr1, arr2)), axis=1)
print(arr)

[[1 2 4 5]
 [3 4 6 7]]


In [69]:
#Numpy array broadcasting
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([4, 5])
arr = arr1 + arr2
arr

array([[5, 7],
       [7, 9]])

In [70]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array(4)
arr = arr1 + arr2
arr

array([[5, 6],
       [7, 8]])

In [71]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [72]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [74]:
arr1 = np.array([[1, 2], [3, 4]])

In [75]:
print(np.sort(arr1))

[[1 2]
 [3 4]]


In [77]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([4,5,6,8])
arr = np.vstack((arr1,arr2))
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 8]])

In [78]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([4,5,6,8])
arr = np.hstack((arr1,arr2))
arr

array([1, 2, 3, 4, 4, 5, 6, 8])

In [79]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([4,5,6,8])
arr = np.dstack((arr1,arr2))
arr

array([[[1, 4],
        [2, 5],
        [3, 6],
        [4, 8]]])

In [80]:
a = np.linspace(1,5,1000)
a

array([1.        , 1.004004  , 1.00800801, 1.01201201, 1.01601602,
       1.02002002, 1.02402402, 1.02802803, 1.03203203, 1.03603604,
       1.04004004, 1.04404404, 1.04804805, 1.05205205, 1.05605606,
       1.06006006, 1.06406406, 1.06806807, 1.07207207, 1.07607608,
       1.08008008, 1.08408408, 1.08808809, 1.09209209, 1.0960961 ,
       1.1001001 , 1.1041041 , 1.10810811, 1.11211211, 1.11611612,
       1.12012012, 1.12412412, 1.12812813, 1.13213213, 1.13613614,
       1.14014014, 1.14414414, 1.14814815, 1.15215215, 1.15615616,
       1.16016016, 1.16416416, 1.16816817, 1.17217217, 1.17617618,
       1.18018018, 1.18418418, 1.18818819, 1.19219219, 1.1961962 ,
       1.2002002 , 1.2042042 , 1.20820821, 1.21221221, 1.21621622,
       1.22022022, 1.22422422, 1.22822823, 1.23223223, 1.23623624,
       1.24024024, 1.24424424, 1.24824825, 1.25225225, 1.25625626,
       1.26026026, 1.26426426, 1.26826827, 1.27227227, 1.27627628,
       1.28028028, 1.28428428, 1.28828829, 1.29229229, 1.29629

In [88]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
import pandas as pd
data = np.random.rand(6,4)
for x in range(data.shape[1]):
  #print(data[:,x])
  nan_val= np.random.choice(6,2,replace=False)
  data[nan_val,x]=np.nan
df = pd.DataFrame(data, columns=["A","B","C","D"])
df

,A,B,C,D
0,0.486726,0.850111,0.662252,NaN
1,0.677076,NaN,0.047813,0.013560
2,0.083897,0.335662,0.514052,NaN
3,0.056950,NaN,NaN,0.269649
4,NaN,0.352568,0.404148,0.126027
5,NaN,0.278964,NaN,0.595937


In [95]:
a= np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [97]:
a= np.full((2,2),7)
a

array([[7, 7],
       [7, 7]])

In [76]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]
